### ISSUE TITLE
Undeclared identifier IL_003b after updating to 1.3.5

### ISSUE THREAD

**Issue by jamietre** [Fody/Costura#126]
A project works fine with 1.3.3. After updating to 1.3.5, I get this error when compiling:

    Error	2	D:\Users\~\AppData\Local\Temp\tmp28EB\TildeSupport.il(4481) : error : Undeclared identifier IL_003b
    D:\Users\~\code\obj\x64\Debug\Common.cs(184) : error : syntax error at token ':' in:         IL_003b:  leave.s    IL_0059
	TildeSupport

The project is https://github.com/jamietre/tcc-plugin

**Comment by maca134** [comment]
I am also getting this error

**Comment by maca134** [comment]
Install-Package Costura.Fody -Version 1.3.2
will install an older version

**Comment by distantcam** [comment]
Fixed in 2.0.0-beta0014

**Comment by epicturkey** [comment]
Getting the same error in 2.0.0-beta0018 [Still]
